### PR TITLE
Rename iotf connector to iotp

### PR DESCRIPTION
**Pull request by ddebrunner**
The builds with ant & gradle and passes the test.

### CODE REVIEW

**Comment by Cazen** [comment]
Hi @ddebrunner :)
How about modify ```include 'connectors:iotf' -> include 'connectors:iotp'``` in settings.gradle

**Comment by ddebrunner** [comment]
Thanks @Cazen , that fixed it.

**Comment by dlaboss** [comment]
@ddebrunner , things don't build in my eclipse workspace after a rebase that includes these changes.  ``samples/.classpath`` has a residual ``iotf`` in an excluding statement for range sensor.  Hence eclipse tries to build the ``samples/scenarios/iotp/range/sensor`` code and fails (due to the absence of pi4j in my environment).

**Comment by dlaboss** [comment]
fixed the .classpath with PR-177

**Pull request merged**
