### PR TITLE
Added Notices

### PR DESCRIPTION
**Pull request by kathyssaunders**
Updated the NOTICE file with additions for packages checked into the Quarks repository.  I determined what to add by going through the source tree looking for third party code, and reviewing license and notice files.

### CODE REVIEW

**Comment by ddebrunner** [comment]
I saw something recently that said the NOTICE file must only include notices that must be there, so I'd like to hold off on merging this to understand if each notice must be copied there.

**Comment by ddebrunner** [comment]
http://www.apache.org/dev/licensing-howto.html

**Comment by ddebrunner** [comment]
For example, why is software distributed under the Eclipse Public Licence listed in the notice?

It's a category B licence:
http://www.apache.org/legal/resolved.html#category-b

**Comment by kathyssaunders** [comment]
On Wed, Mar 30, 2016 at 4:36 PM, Dan Debrunner <notifications@github.com>
wrote:

> I saw something recently that said the NOTICE file must only include
> notices that must be there, so I'd like to hold off on merging this to
> understand if each notice must be copied there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-quarks/pull/58#issuecomment-203685276>
>
Yes, I saw conflicting information on that, so erred on the side of
safety.  If we can remove some of them, I'm fine with that.  I looked at
other projects and they seemed to vary a bit.

**Comment by ddebrunner** [comment]
Currently the top-level LICENSE and NOTICE file are copied into each jar.

Seems that with these files fully completed (this pr and #57) that may no longer be the correct approach.

For example the scala licence added by #57 only is applicable for the Kafka connector, so why should it appear in every other jar?

**Comment by kathyssaunders** [comment]
On Thu, Mar 31, 2016 at 11:22 AM, Dan Debrunner <notifications@github.com>
wrote:

> Currently the top-level LICENSE and NOTICE file are copied into each jar.
>
> Seems that with these files fully completed (this pr and #57
> <https://github.com/apache/incubator-quarks/pull/57>) that may no longer
> be the correct approach.
>
> For example the scala licence added by #57
> <https://github.com/apache/incubator-quarks/pull/57> only is applicable
> for the Kafka connector, so why should it appear in every other jar?
>
> I agree this is not the right approach. Does anyone have a suggestion?  I
will do some more research into what other projects do.

**Comment by kathyssaunders** [comment]
Closing this pull request; I plan to update notice file in smaller increments.

**Pull request closed without merging**
