### PR TITLE
[QUARKS-128] Update to current Watson IoT Platform release 0.1.1

### PR DESCRIPTION
**Pull request by queeniema**
Updated:

* `com.ibm.iotf.client-0.0.9.jar` to `watson-iot-0.1.1.jar`
* `httpclient-4.3.6.jar` to `httpclient-4.5.1.jar`
* `httpcore-4.3.3.jar` to `httpcore-4.4.4.jar`
* `joda-time-2.6.jar` to `joda-time-2.9.2.jar`

### CODE REVIEW

**Comment by queeniema** [comment]
The build failed because a HTTP connecter test failed, which this PR should not affect. Is there a way to run the Travis build again?

**Comment by queeniema** [comment]
Thank you @dlaboss. Will try running again.

**Comment by dlaboss** [comment]
Just checking before I merge... have you tried one of the Iotf samples or equivalent to verify an Iotf app works fine with the changes?  The Iotf connector doesn't have any automated tests.

**Comment by queeniema** [comment]
Yes, I've checked with IotfQuickstart, IotfSensors, and IotfFullScenario. They all work, so this is ready to be merged!

**Comment by dlaboss** [comment]
Primo! thx.

**Pull request merged**
