### PR TITLE
[QUARKS-237] Create top level Junit report and Jacoco parity

### PR DESCRIPTION
**Pull request by Cazen**

### CODE REVIEW

**Comment by Cazen** [comment]
I will further develop about test through [QUARKS-239](https://issues.apache.org/jira/browse/QUARKS-239) later

**Comment by dlaboss** [comment]
@cazen I rebased my workspace to pickup the latest master but I get a failure when I `gradle build` (or `gradle jacocoTestReport`).  Is it supposed to work?  The mentioned test.exec data does exist in my workspace.

$ gradle build
… // lots of stuff
:utils:metrics:assemble
:utils:metrics:copyJar
:utils:streamscope:assemble
:utils:streamscope:copyJar
:jacocoTestReport FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/dlaboss/git/incubator-quarks/build.gradle' line: 230

* What went wrong:
Execution failed for task ':jacocoTestReport'.
> Unable to read execution data file /Users/dlaboss/git/incubator-quarks/analytics/math3/build/jacoco/test.exec

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11 mins 6.185 secs

**Comment by Cazen** [comment]
Hi @dlaboss :)
Thank you for review. I remember that it works in my Mac and Linux desktop but I couldn't check it right now. I will check it again when come back to home

Could you please run it again with gradle wrapper like ```./gradlew build --stacktrace``` after making sure your working directory clean?
It looks some gradle and jacoco version can cause conflict.
(I found some similar case from googling. Please refer to: [link1](https://discuss.gradle.org/t/jacoco-coverage-for-android-test-cases-fails-in-gradle-version-2-13-and-2-14/18272/7), [link2](https://www.mkyong.com/gradle/gradle-jacoco-incompatible-version-1006/)

**Comment by dlaboss** [comment]
Thanks! Yes, it was a version issue.  I just need to use `./gradlew` (v2.13) instead of my `gradle` (v2.10)

**Pull request merged**
