### PR TITLE
QUARKS-201 added keyboard support to console

### PR DESCRIPTION
**Pull request by home4slc**
Added tab indices to a lot of the html on the page and keypress handlers for some of the controls.
Now the user can tab to open the hover for the job state and also tab (then push enter) to see all the properties in the graph.  Using the browser specific keys to close a popup/window will close the window containing the table.

i.e, On MAC it is command + W

### CODE REVIEW

**Comment by dlaboss** [comment]
pls close/reopen to return travis-ci (wget of ant failed)

**Comment by home4slc** [comment]
@dlaboss - it's still failing after closing / reopening. Do you have any suggestions.  It's the same error.  Thanks.

**Comment by dlaboss** [comment]
looks like infr is now working.  close/reopen to rerun travis-ci.

**Comment by home4slc** [comment]
Closing and will reopen - hopefully it will work now.

**Comment by home4slc** [comment]
Oops, now it is saying I have unmerged commits.  Can someone advise me on what I need to do to reopen the pull request correctly?  Thanks, Susan

**Comment by dlaboss** [comment]
Reopen the PR.  If it then says that it can't be merged due to conflicts (some other PR has been merged that changes one or more of the same file as this PR) you need to rebase your PR branch so it's up to date with respect to the master branch... standard github fork-workflow stuff.

**Comment by home4slc** [comment]
Boo-hoo.  It failed again:

The command "wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz" failed and exited with 8 during .

**Comment by home4slc** [comment]
One more try ...

**Pull request merged**
