### PR TITLE
[QUARKS-47] Remove unnecessary null check in ConnectorStream.split(enumClass, splitter)

### PR DESCRIPTION
**Pull request by Cazen**

### CODE REVIEW

**Comment by Cazen** [comment]
@ddebrunner Good day! Could you please review this change?
It related PR #11.

**Comment by wmarshall484** [comment]
+1 to merge, E is already defined as an Enum, so the null check is unnecessary

**Comment by wmarshall484** [comment]
Hm, odd that asf-git didn't close this automatically.

**Comment by Cazen** [comment]
Thank you @wmashall484
Have a good day!

**Pull request merged**
