### PR TITLE
[WIP] [QUARKS-195] Metrics.counter needs TStream.peek(oplet)

### PR DESCRIPTION
**Pull request by dlaboss**

### CODE REVIEW

**Comment by ddebrunner** [comment]
What's the rationale for adding the method. What does it enable that a function does not?

**Comment by dlaboss** [comment]
@ddebrunner pls see QUARKS-195 for the rationale.

**Comment by ddebrunner** [comment]
I looked there and didn't see anything. It says a pipe is not correct, but nothing why a new peek method is required.

**Comment by dlaboss** [comment]
I updated QUARKS-195 to clarify things.  Please check it again.

**Comment by dlaboss** [comment]
unrelated test failure.  closing/reopening to rerun.

**Comment by dlaboss** [comment]
Changing to WIP until concerns raised in QUARKS-195 are resolved.

**Comment by dlaboss** [comment]
rerun travis-ci

**Comment by dlaboss** [comment]
rerun travis-ci

**Comment by dlaboss** [comment]
testDeadtimeDynamic failed got tuples [1,5,8] should be [1,4,6,9].  This is another timing sensitive test where an attempt has already been made to desentize it.  Gonna exclude it from travis-ci.

**Comment by dlaboss** [comment]
hmm... managed to force-push this branch when fixing up my repo following a mishap.  so this PR is now closed and I'll open a new one for this.

**Pull request closed without merging**
