### PR TITLE
[QUARKS-198] Accessibility enhancements for Javadoc

### PR DESCRIPTION
**Pull request by queeniema**

### CODE REVIEW

**Comment by dlaboss** [comment]
pls close/reopen to get a travis-ci rerun (couldn't download ant)

**Comment by dlaboss** [comment]
looks like infr is now working.  close/reopen to rerun travis-ci.

**Comment by ddebrunner** [comment]
Is this a WIP?

**Comment by queeniema** [comment]
@ddebrunner Yes, still a WIP. I plan to execute more tests to see if more changes need to be made.

**Pull request merged**
