### PR TITLE
QUARKS-21 [WIP] SVT GPS/OBD application

### PR DESCRIPTION
**Pull request by mnwone**
QUARKS-21 Initial infrastructure checkin

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can you add headers to the new source files:

http://apache.org/legal/src-headers.html#headers

**Comment by ddebrunner** [comment]
FYI - my comment was only about new source files, not existing files.

The changes can be kept, but try not to introduce unrelated changes into a pull request.

**Comment by mnwone** [comment]
How to get this pull 'restarted'?  Do I have to wait for the Travis build issue #38 to be resolved or should I do a dummy commit?

**Comment by ddebrunner** [comment]
From a quick search I found this:

http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by ddebrunner** [comment]
Not sure it matters but you picked a different style of including the apache licence header to others.

Others just included the apache text as is between /* and */ whereas you added * to the beginning of each line.

I know I just used the /*  and */ because I'm too lazy to add something to each line, but maybe your IDE did that?

**Comment by ddebrunner** [comment]
The conflicts were caused by the wholesale changes of the IBM copyright statements to Apache licence headers.

It's good practice to not add unrelated changes into a pull request, such a whitespace changes etc., it's best to keep commits, pull requests, issues focused on a single item.

**Pull request closed without merging**
